routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes(['reset' => false, 'register' => false]);

Route::view('test', 'test');

Route::group(['middleware'=>'auth'], function (){

    Route::get('/', 'DashboardController@index')->name('/');

    /*    Resource Controllers starts     */

    Route::resource('products', 'ProductController');

    Route::resource('product_categories', 'ProductCategoryController');

    Route::resource('expenses', 'ExpenseController');

    Route::resource('expense_categories', 'ExpenseCategoryController');

    Route::resource('contractors','ContractorController');

    Route::resource('contractor_types', 'ContractorTypeController');

    Route::resource('measurement_units', 'MeasurementUnitController');

    Route::resource('product_types', 'ProductTypeController');

    Route::resource('product_models', 'ProductModelController');

    Route::resource('company_settings','CompanySettingController');

    Route::resource('vehicles','VehicleController');

    Route::resource('orders','OrderController');
    
	Route::resource('departments','DepartmentController');

	Route::resource('work_lists','WorkListController');

	Route::resource('orderdetails','OrderDetailController');

	Route::resource('customers','CustomerController');

	Route::resource('suppliers', 'SupplierController');

    Route::resource('employees', 'EmployeeController');
    
    Route::resource('attendances', 'AttendanceController');
    /** Salary Routes starts */

    Route::resource('salaries', 'SalaryController');

    Route::get('monthly_salary_dues', 'SalaryController@monthly_salary_dues')->name('monthly_salary_dues');
    
    /** Salary Routes starts */
    Route::resource('parts', 'PartController');

    Route::resource('orders','OrderController');

    Route::resource('materials', 'MaterialController');

    Route::resource('material_types', 'MaterialTypeController');

    Route::resource('material_stocks', 'MaterialStockController');

    Route::resource('brands', 'BrandController');

    Route::resource('units', 'UnitController');

/*    Resource Controllers ends     */


/*    Reports Routes starts     */

    Route::get('report/material', 'ReportController@Material')->name('materials_report');

    Route::get('report/contractor', 'ReportController@Contractor')->name('contractors_report');

    Route::get('delivered_products', 'ReportController@delivered_products')->name('delivered_products');

    Route::get('report/material_product', 'ReportController@MaterialProduct')->name('material_product');


/*    Reports Routes ends     */

/** Material Assignment Routes starts */

    Route::get('assign_material_history', 'AssignMaterialController@index')->name('assign_material_history');

    Route::get('assign_material', 'AssignMaterialController@create')->name('assign_material');

    Route::post('assign_material', 'AssignMaterialController@assignMaterialToProduct')->name('assign_material');

/** Material Assignment Routes ends */

	Route::get('orderDetailupdate/{id}','OrderDetailController@orderDetailupdate');

	Route::get('customer/{phone}','CustomerController@index');
});

/** Cache Clear Routes Starts */

Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    session()->flash('success','Cache Cleared successfull');
    return redirect()->route('/');
});
/** Cache Clear Routes Ends */

app/WorkList.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class WorkList extends Model
{
    protected $fillable = ['name','department_id','rate1','rate2','rate3'];
   
    public function setRateupto1_5kccAttribute($value){
        $this->attributes['rateupto1_5kcc'] = (double)$value;
    }

    // A worklist has many job Details
    function workdetails()
    {
        return $this->hasMany('App\JobDetail');
    }
    
    public function order()
    {
        return $this->belongsTo('App\Order');
    }
    
    public function orderDetail()
    {
        return $this->hasMany('App\OrderDetail','work_list_id');
    }
    
    public function department()
    {
        return $this->belongsTo('App\Department');
    }
}

app/Http/Controllers/WorkListController.php
<?php

namespace App\Http\Controllers;

use App\WorkList;
use App\Department;
use Illuminate\Http\Request;

class WorkListController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $departments = Department::all();
        $work_lists = WorkList::where(function($worklist){
            if(request('name')){
                $worklist->where('name', 'like', "%".request('name')."%");
            }
            if(request('department_id')){
                $worklist->where('department_id', request('department_id'));
            }
        })->get();
        return view('worklists.index',compact('work_lists','departments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departments = Department::all();
        return view('worklists.create', compact('departments'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        WorkList::create(request()->validate([
            'name'=>'required',
            'department_id'=>'required',
            'rate1'=>'numeric',
            'rate2'=>'numeric',
            'rate3'=>'numeric'
        ])); 
        return back()->with('success','Worklist Added Successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\WorkList  $workList
     * @return \Illuminate\Http\Response
     */
    public function show(WorkList $workList)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\WorkList  $workList
     * @return \Illuminate\Http\Response
     */
   public function edit(WorkList $workList)
    {
        $departments = Department::all();
        return view('worklists.edit', compact('workList','departments'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\WorkList  $workList
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, WorkList $workList) //$id need to be solved
    {

       $this->validate($request,[
            'name'=>'required',
            'department_id'=>'required',
            'rate1'=>'numeric',
            'rate2'=>'numeric',
            'rate3'=>'numeric'
        ]); 

        $workList->name = $request->name;
        $workList->department_id = $request->department_id;
        $workList->rate1= $request->rate1;
        $workList->rate2= $request->rate2;
        $workList->rate3= $request->rate3;
        $workList->update();
        session()->flash('success','Worklist Added Successfully.');
        return redirect()->route('work_lists.index');
            
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\WorkList  $workList
     * @return \Illuminate\Http\Response
     */
    public function destroy(WorkList $workList) //$id Need to be solved or removed
    {
        $workingList = WorkList::find($id);
        $workingList->delete();
        return back()->with('success','Work list deleted successfully!');
    }
}

resources/views/worklists/create.blade.php
@extends('layouts.fixed')
@section('title', 'Worklists')
@section('breadcrumb')
    <li class="breadcrumb-item active">Worklists Create</li>
@endsection
@section('content')
<section class="content mt-1">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- form start -->
                <form role="form" action="{{ route('suppliers.store') }}" method="post" enctype="multipart/form-data">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Worklists Register Form</h3>
                        </div><!-- /.card-header -->
                        <div class="card-body">
                            @csrf
                            <div class="row">
                                <div class="col-md-12">
                                    <!-- general form elements -->
                                    <div class="box box-info">
                                        <div class="box-header with-border">
                                            <h3 class="box-title"></h3>
                                        </div>
                                        <!-- /.box-header -->
                                        <!-- form start -->
                                            @csrf
                                            <div class="box-body">
                                                 <div class="form-group row">
                                                    <label for="name" class="col-sm-2 control-label">Name</label>
                                
                                                    <div class="col-sm-10">
                                                    <input type="text" class="form-control" id="name" placeholder="Name">
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label for="cc" class="col-sm-2 control-label">Department</label>
                                                    <div class="col-sm-10">
                                                        <select class="form-control">
                                                            <option value=''>select Department</option>
                                                            @forelse($departments as $department)
                                                                <option value="{{$department->id}}">{{ $department->name }}</option>
                                                            @empty

                                                            @endforelse
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label for="no" class="col-sm-2 control-label">Rate 1</label>
                                
                                                    <div class="col-sm-10">
                                                    <input type="text" class="form-control" id="test" placeholder="Enter Rate for 800CC to 1500 CC">
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label for="no" class="col-sm-2 control-label">Rate 2</label>
                                
                                                    <div class="col-sm-10">
                                                    <input type="text" class="form-control" id="test" placeholder="Enter Rate for 1600 to 2500 CC">
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label for="no" class="col-sm-2 control-label">Rate 3</label>
                                
                                                    <div class="col-sm-10">
                                                    <input type="text" class="form-control" id="test" placeholder="Enter Rate for 2600 CC +">
                                                    </div>
                                                </div>
                                            </div>
                                            <!-- /.box-body -->
                                            <div class="box-footer"></div>
                                            <!-- /.box-footer -->
                                    </div>
                                    <!-- /.box -->
                                </div>
                            </div>
                        </div><!-- /.card-body -->
                        <div class="card-footer">
                            <a href="{{ route('suppliers.index') }}" class="btn btn-danger">Cancel</a>
                            <button type='reset' class="btn btn-primary">Reset Form</button>
                            <button type="submit" class="btn btn-success float-right">Register</button>
                        </div>
                    </div><!-- /.card -->
                </form>
            </div><!-- /.col-md-12 -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
@endsection
@section('script')
<script>

</script>
@endsection

resources/views/worklists/edit.blade.php
@extends('layouts.fixed')
@section('title', 'Work List')
@section('breadcrumb')
    <li class="breadcrumb-item active">Work List Update</li>
@endsection
@section('content')
<section class="content mt-1">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- form start -->
                <form role="form" action="{{ route('work_lists.update', $workList->id) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('put')
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Work List Update Form</h3>
                        </div><!-- /.card-header -->
                        <div class="card-body">
                            @csrf
                            @method('put')
                            <div class="row">
                                <div class="col-md-12">
                                    <!-- general form elements -->
                                    <div class="box box-info">
                                        <div class="box-header with-border">
                                            <h3 class="box-title"></h3>
                                        </div>
                                        <!-- /.box-header -->
                                        <!-- form start -->
                                        <div class="box-body">
                                           <div class="form-group row">
                                                    <label for="name" class="col-sm-2 control-label">Name</label>
                                
                                                    <div class="col-sm-10">
                                                    <input type="text" class="form-control" id="name" name="name" value="{{old('name') ?? $workList->name }}" placeholder="Name">
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label for="cc" class="col-sm-2 control-label">Department</label>
                                                    <div class="col-sm-10">
                                                        <select class="form-control" name="department_id">
                                                            <option value=''>select Department</option>
                                                            @forelse($departments as $department)
                                                                <option {{ $workList->department_id == $department->id ? 'selected' : ''}} value="{{$department->id}}">{{ $department->name }}</option>
                                                            @empty

                                                            @endforelse
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label for="no" class="col-sm-2 control-label">Rate 1</label>
                                
                                                    <div class="col-sm-10">
                                                    <input type="text" class="form-control" id="" name="rate1" value="{{ $workList->rate1 }}" placeholder="Enter Rate for 800CC to 1500 CC">
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label for="no" class="col-sm-2 control-label">Rate 2</label>
                                
                                                    <div class="col-sm-10">
                                                    <input type="text" class="form-control" id="" name="rate2" value="{{ $workList->rate2 }}" placeholder="Enter Rate for 1600 to 2500 CC">
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label for="no" class="col-sm-2 control-label">Rate 3</label>
                                
                                                    <div class="col-sm-10">
                                                    <input type="text" class="form-control" id=""  name="rate3" value="{{ $workList->rate3 }}" placeholder="Enter Rate for 2600 CC +">
                                                    </div>
                                                </div> 
                                        </div>
                                        <!-- /.box-body -->
                                        <div class="box-footer"></div>
                                        <!-- /.box-footer -->
                                    </div>
                                    <!-- /.box -->
                                </div>
                            </div>
                        </div><!-- /.card-body -->
                        <div class="card-footer">
                            <a href="{{ route('work_lists.index') }}" class="btn btn-danger">Cancel</a>
                            <a href="{{ route('work_lists.index') }}" class="btn btn-primary">Reset Form</a>
                            <button type="submit" class="btn btn-success float-right">Update</button>
                        </div>
                    </div><!-- /.card -->
                </form>
            </div><!-- /.col-md-12 -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
@endsection
@section('script')
<script>

</script>
@endsection

resources/views/worklists/index.blade.php
@extends('layouts.fixed')
@section('title', 'Work List')

@section('breadcrumb')
    <li class="breadcrumb-item active">Work Lists</li>
@endsection
@section('content')
    <section class="content mt-1">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary col-md-12">
                        <div class="card-header row">
                            <h3 class="card-title col-md-3">All Work Lists <a title="Click to add new Worklist" class="btn btn-sm " href="{{ route('work_lists.create')}}">
                                <span class="fas fa-plus"></span></a>
                            </h3>
                            <div class="col-md-9">
                                <form class="form-inline float-right" method="GET" action="{{ route('work_lists.index') }}">
                                    <div class="form-group mx-sm-3">
                                    <label for="name" class="sr-only">Name</label>
                                    <input class="form-control" placeholder="Work List Name" name="name" type="text" value="{{ request('name') }}" id="name">
                                    </div>
                                    <div class="form-group mx-sm-3">
                                        <label for="department_id" class="sr-only">Department</label>
                                        <select class="form-control" name="department_id" id="department_id">
                                            <option value="">Select Department</option>
                                            @forelse($departments as $department)
                                            <option {{ request('department_id') == $department->id ? 'selected' : '' }} value="{{$department->id}}">{{ $department->name }}</option>
                                            @empty
                                            @endforelse
                                        </select>
                                    </div>
                                    <button type="submit" class="btn btn-info btn-round"><i class="fa fa-search"></i></button>
                                    @if(request()->query())
                                        <a href="{{ route('work_lists.index') }}" class='btn btn-info btn-round' >All</a>
                                    @endif
                                  </form>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="tab-content">
                                <div class="table-responsive">
                                    <table class="table table-sm table-striped">
                                        <thead>
                                            <tr class='bg-secondary'>
                                                <th>#SL</th>
                                                <th>Working List name</th>
                                                <th>Department</th>
                                                <th>800 CC To 1500 CC</th>
                                                <th>1600 CC To 2500 CC</th>
                                                <th>2600 CC+</th>
                                                <th class="text-center">Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            
                                        @php $sl = 0 @endphp
                                        @forelse($work_lists as $work_list)
                                        <tr>
                                            <td>{{ ++$sl }}</td>
                                            <td>{{ $work_list->name}}</td>
                                            <td>{{ $work_list->department->name }}</td>
                                            <td class="text-right">{{ number_format($work_list->rate1,2) }}</td>
                                            <td class="text-right">{{ number_format($work_list->rate2,2) }}</td>
                                            <td class="text-right">{{ number_format($work_list->rate3,2) }}</td>
                                            <td class="text-center">
                                                <form action="#" method="post"
                                                    onsubmit=" return confirm('Are you sure to delete?')">
                                                    @csrf
                                                    @method('delete')
                                                    <div class="btn-group">
                                                        {{--  <a href="#" class="btn btn-success"><i class="fa fa-eye"></i></a>  --}}
                                                        {{--  <a href="#" class="btn btn-success" data-toggle="tooltip" data-placement="auto top" title="Show Status"><i class="fa fa-list"></i></a>  --}}
                                                        <a href="{{ route('work_lists.edit',1) }}" class="btn btn-warning"><i class="fa fa-edit"></i></a>
                                                        {{--  <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>  --}}
                                                    </div>
                                                </form>
                                            </td>
                                        </tr>
                                        @empty

                                        @endforelse
                                            
                                        </tbody>
                                    </table>
                                    {{-- {{ $products->appends(request()->query())->links() }} --}}
                                </div>
                                <!-- /.tab-pane -->
                            </div>
                            <!-- /.tab-content -->
                        </div><!-- /.card-body -->
                    </div>
                    <!-- /.nav-tabs-custom -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
@endsection