routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes(['reset' => false, 'register' => false]);

Route::view('test', 'test');

Route::group(['middleware'=>'auth'], function (){

    Route::get('/', 'DashboardController@index')->name('/');

    /*    Resource Controllers starts     */

    Route::resource('products', 'ProductController');

    Route::resource('product_categories', 'ProductCategoryController');

    Route::resource('expenses', 'ExpenseController');

    Route::resource('expense_categories', 'ExpenseCategoryController');

    Route::resource('contractors','ContractorController');

    Route::resource('contractor_types', 'ContractorTypeController');

    Route::resource('measurement_units', 'MeasurementUnitController');

    Route::resource('product_types', 'ProductTypeController');

    Route::resource('product_models', 'ProductModelController');

    Route::resource('company_settings','CompanySettingController');

    Route::resource('vehicles','VehicleController');

    Route::resource('orders','OrderController');
    
	Route::resource('departments','DepartmentController');

	Route::resource('work_lists','WorkListController');

	Route::resource('orderdetails','OrderDetailController');

	Route::resource('customers','CustomerController');

	Route::resource('suppliers', 'SupplierController');

    Route::resource('employees', 'EmployeeController');
    
    Route::resource('attendances', 'AttendanceController');
    /** Salary Routes starts */

    Route::resource('salaries', 'SalaryController');

    Route::get('monthly_salary_dues', 'SalaryController@monthly_salary_dues')->name('monthly_salary_dues');
    
    /** Salary Routes starts */
    Route::resource('parts', 'PartController');

    Route::resource('orders','OrderController');

    Route::resource('materials', 'MaterialController');

    Route::resource('material_types', 'MaterialTypeController');

    Route::resource('material_stocks', 'MaterialStockController');

    Route::resource('brands', 'BrandController');

    Route::resource('units', 'UnitController');

/*    Resource Controllers ends     */


/*    Reports Routes starts     */

    Route::get('report/material', 'ReportController@Material')->name('materials_report');

    Route::get('report/contractor', 'ReportController@Contractor')->name('contractors_report');

    Route::get('delivered_products', 'ReportController@delivered_products')->name('delivered_products');

    Route::get('report/material_product', 'ReportController@MaterialProduct')->name('material_product');


/*    Reports Routes ends     */

/** Material Assignment Routes starts */

    Route::get('assign_material_history', 'AssignMaterialController@index')->name('assign_material_history');

    Route::get('assign_material', 'AssignMaterialController@create')->name('assign_material');

    Route::post('assign_material', 'AssignMaterialController@assignMaterialToProduct')->name('assign_material');

/** Material Assignment Routes ends */

	Route::get('orderDetailupdate/{id}','OrderDetailController@orderDetailupdate');

	Route::get('customer/{phone}','CustomerController@index');
});

/** Cache Clear Routes Starts */

Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    session()->flash('success','Cache Cleared successfull');
    return redirect()->route('/');
});
/** Cache Clear Routes Ends */

resources/views/includes/footer.blade.php
<strong class="">Copyright &copy; 2018-2019 <a href="#"></a>.</strong>
<span class="">All rights reserved.</span>
<div class="float-right d-none d-sm-inline-block ">
    <b>Version</b> 1.0.1
</div>

resources/views/includes/header.blade.php
<!-- Left navbar links -->
<ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
    </li>
</ul>
<section class="content-header">
    <div class="row ">
        <div class="col-sm-12">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="{{ route('/') }}">Home</a></li>
                @yield('breadcrumb')
            </ol>
        </div>
    </div>
</section>
<!-- Right navbar links -->
<ul class="navbar-nav ml-auto">
    <!-- Messages Dropdown Menu -->
    {{--<li class="nav-item dropdown">--}}
        {{--<a class="nav-link" data-toggle="dropdown" href="#">--}}
            {{--<i class="far fa-envelope"></i>--}}
            {{--<span class="badge badge-danger navbar-badge">3</span>--}}
        {{--</a>--}}
        {{--<div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">--}}
            {{--<a href="#" class="dropdown-item">--}}
                {{--<!-- Message Start -->--}}
                {{--<div class="media">--}}
                    {{--<img src="{{ asset('dist/img/user1-128x128.jpg') }}" alt="User Avatar" class="img-size-50 mr-3 img-circle">--}}
                    {{--<div class="media-body">--}}
                        {{--<h3 class="dropdown-item-title">--}}
                            {{--Brad Diesel--}}
                            {{--<span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>--}}
                        {{--</h3>--}}
                        {{--<p class="text-sm">Call me whenever you can...</p>--}}
                        {{--<p class="text-sm text-muted"><i class="far fa-clock-o mr-1"></i> 4 Hours Ago</p>--}}
                    {{--</div>--}}
                {{--</div>--}}
                {{--<!-- Message End -->--}}
            {{--</a>--}}
            {{--<div class="dropdown-divider"></div>--}}
            {{--<a href="#" class="dropdown-item">--}}
                {{--<!-- Message Start -->--}}
                {{--<div class="media">--}}
                    {{--<img src="{{ asset('dist/img/user8-128x128.jpg') }}" alt="User Avatar" class="img-size-50 img-circle mr-3">--}}
                    {{--<div class="media-body">--}}
                        {{--<h3 class="dropdown-item-title">--}}
                            {{--John Pierce--}}
                            {{--<span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>--}}
                        {{--</h3>--}}
                        {{--<p class="text-sm">I got your message bro</p>--}}
                        {{--<p class="text-sm text-muted"><i class="far fa-clock-o mr-1"></i> 4 Hours Ago</p>--}}
                    {{--</div>--}}
                {{--</div>--}}
                {{--<!-- Message End -->--}}
            {{--</a>--}}
            {{--<div class="dropdown-divider"></div>--}}
            {{--<a href="#" class="dropdown-item">--}}
                {{--<!-- Message Start -->--}}
                {{--<div class="media">--}}
                    {{--<img src="{{ company()->logo }}" alt="User Avatar" class="img-size-50 img-circle mr-3">--}}
                    {{--<div class="media-body">--}}
                        {{--<h3 class="dropdown-item-title">--}}
                            {{--Nora Silvester--}}
                            {{--<span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>--}}
                        {{--</h3>--}}
                        {{--<p class="text-sm">The subject goes here</p>--}}
                        {{--<p class="text-sm text-muted"><i class="far fa-clock-o mr-1"></i> 4 Hours Ago</p>--}}
                    {{--</div>--}}
                {{--</div>--}}
                {{--<!-- Message End -->--}}
            {{--</a>--}}
            {{--<div class="dropdown-divider"></div>--}}
            {{--<a href="#" class="dropdown-item dropdown-footer">See All Messages</a>--}}
        {{--</div>--}}
    {{--</li>--}}
    {{--<!-- Notifications Dropdown Menu -->--}}
    {{--<li class="nav-item dropdown">--}}
        {{--<a class="nav-link" data-toggle="dropdown" href="#">--}}
            {{--<i class="far fa-bell"></i>--}}
            {{--<span class="badge badge-warning navbar-badge">15</span>--}}
        {{--</a>--}}
        {{--<div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">--}}
            {{--<span class="dropdown-item dropdown-header">15 Notifications</span>--}}
            {{--<div class="dropdown-divider"></div>--}}
            {{--<a href="#" class="dropdown-item">--}}
                {{--<i class="fas fa-envelope mr-2"></i> 4 new messages--}}
                {{--<span class="float-right text-muted text-sm">3 mins</span>--}}
            {{--</a>--}}
            {{--<div class="dropdown-divider"></div>--}}
            {{--<a href="#" class="dropdown-item">--}}
                {{--<i class="fas fa-users mr-2"></i> 8 friend requests--}}
                {{--<span class="float-right text-muted text-sm">12 hours</span>--}}
            {{--</a>--}}
            {{--<div class="dropdown-divider"></div>--}}
            {{--<a href="#" class="dropdown-item">--}}
                {{--<i class="fas fa-file mr-2"></i> 3 new reports--}}
                {{--<span class="float-right text-muted text-sm">2 days</span>--}}
            {{--</a>--}}
            {{--<div class="dropdown-divider"></div>--}}
            {{--<a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>--}}
        {{--</div>--}}
    {{--</li>--}}

    {{--<!-- Notifications Dropdown Menu -->--}}
    {{--<li class="nav-item dropdown">--}}
        {{--<a class="nav-link" data-toggle="dropdown" href="#">--}}
            {{--<i class="far fa-flag"></i>--}}
            {{--<span class="badge badge-success navbar-badge">9</span>--}}
        {{--</a>--}}
        {{--<div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">--}}
            {{--<span class="dropdown-item dropdown-header">You have 9 tasks</span>--}}
            {{--<div class="dropdown-divider"></div>--}}
            {{--<a href="#" class="dropdown-item">--}}
                {{--<i class="fas fa-envelope mr-2"></i> 4 new messages--}}
                {{--<span class="float-right text-muted text-sm">3 mins</span>--}}
            {{--</a>--}}
            {{--<div class="dropdown-divider"></div>--}}
            {{--<a href="#" class="dropdown-item">--}}
                {{--<i class="fas fa-users mr-2"></i> 8 friend requests--}}
                {{--<span class="float-right text-muted text-sm">12 hours</span>--}}
            {{--</a>--}}
            {{--<div class="dropdown-divider"></div>--}}
            {{--<a href="#" class="dropdown-item">--}}
                {{--<i class="fas fa-file mr-2"></i> 3 new reports--}}
                {{--<span class="float-right text-muted text-sm">2 days</span>--}}
            {{--</a>--}}
            {{--<div class="dropdown-divider"></div>--}}
            {{--<a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>--}}
        {{--</div>--}}
    {{--</li>--}}

    <!-- User Account: style can be found in dropdown.less -->
    <li class="nav-item dropdown" style="margin-top:4px; padding: 10px">
        <a href="#" class="user dropdown-toggle" data-toggle="dropdown" style="margin:10px;">
            <img src="{{ asset(company()->logo) }}" style="height:33.33px; margin-right:5px;" class="img-circle elevation-2" alt="User Image">
            <span class="hidden-xs">{{ auth()->user()->name }}</span>
        </a>
        <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
            <li class="user-header">
                <p class="text-center">
                    <img src="{{ asset(company()->logo) }}" class="img-cir profile-img" alt="User Image" width="160" height="160">
                </p>
                <p class="profile-dec" style="margin: 10%">
                    {{-- @foreach("Auth::user()->roles as role") --}}
                        <span class="badge badge-info">Admin</span>
                    {{-- @endforeach --}}
                    <br>
                    <small>Member since {{ auth()->user()->created_at ?  auth()->user()->created_at->format('F, Y') : '' }}</small>
                </p>
            </li>
            <!-- Menu Body -->
            {{--<li class="user-body">--}}
                {{--<div class="row">--}}
                    {{--<div class="col-xs-4 text-center" style="margin-left: 40px;">--}}
                        {{--<a href="#">Followers</a>--}}
                    {{--</div>--}}
                    {{--<div class="col-xs-4 text-center" style="margin-left: 30px;">--}}
                        {{--<a href="#">Sales</a>--}}
                    {{--</div>--}}
                    {{--<div class="col-xs-4 text-center" style="margin-left: 30px;">--}}
                        {{--<a href="#">Friends</a>--}}
                    {{--</div>--}}
                {{--</div>--}}
                {{--<!-- /.row -->--}}
            {{--</li>--}}
            <!-- Menu Footer-->
            <li class="user-footer">
                <div class="pull-left" style="display: inline-block; float: left; margin: 10%">
                    {{-- <a href="#" class="btn btn-default btn-flat">Profile</a> --}}
                </div>
                <div class="pull-right" style="display: inline-block; float: right; margin: 10%">
                    <a href="{{ route('logout') }}"
                       class="btn btn-default btn-flat"
                       onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                       {{  __('Logout') }}
                    </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>
                </div>
            </li>
        </ul>
    </li>

    <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#">
            <i class="fas fa-th-large"></i>
        </a>
    </li>
</ul>

resources/views/includes/left-sidebar.blade.php
<!-- Sidebar -->
<div class="sidebar nano">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
            <img src="{{ asset(company()->logo) }}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
            <a href="{{ url('/') }}" class="d-block">{{ company()->name }}</a>
        </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <li class="nav-item {{ isActive(['/']) }}">
                <a href="{{ route('/')}}" class="nav-link {{ isActive(['/']) }}">
                    <i class="nav-icon fas fa-tachometer-alt"></i>
                    <p>
                        Dashboard
                    </p>
                </a>
            </li>
            {{--Contacts menu starts--}}
            <li class="nav-item has-treeview {{ isActive(['employees','employees/*','customers','customers/*','suppliers','suppliers/*']) }}">
                <a href="#" class="nav-link {{ isActive(['employees','employees/*','customers','customers/*','suppliers','suppliers/*']) }}">
                    <i class="nav-icon far fa-bookmark"></i>
                    <p>Contacts<i class="right fas fa-angle-left"></i></p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{{ route('employees.index') }}" class="nav-link {{ isActive(['employees','employees/*']) }}">
                            <i class="far fa-circle nav-icon"></i>
                            <p>All Employees</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('customers.index') }}" class="nav-link {{ isActive(['customers','customers/*']) }}">
                            <i class="far fa-circle nav-icon"></i>
                            <p>All Customers</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('suppliers.index') }}" class="nav-link {{ isActive(['suppliers','suppliers/*']) }}">
                            <i class="far fa-circle nav-icon"></i>
                            <p>All Suppliers</p>
                        </a>
                    </li>
                </ul>
            </li>
            {{--Contacts menu ends--}}

            {{--Attendances menu starts--}}
            <li class="nav-item has-treeview {{ isActive(['attendances','attendances/*']) }}">
                <a href="#" class="nav-link {{ isActive(['attendances','attendances/*']) }}">
                    <i class="nav-icon far fa-handshake"></i>
                    <p>attendances<i class="right fas fa-angle-left"></i></p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{{ route('attendances.index') }}" class="nav-link {{ isActive(['attendances','attendances/*']) }}">
                            <i class="far fa-circle nav-icon"></i>
                            <p>All attendances</p>
                        </a>
                    </li>
                </ul>
            </li>
            {{--Attendances menu ends--}}

            {{--Orders menu starts--}}
            <li class="nav-item has-treeview  {{ isActive(['orders','orders/*']) }}">
                <a href="#" class="nav-link {{ isActive(['orders','orders/*']) }}">
                        <i class="nav-icon fas fa-cart-plus"></i>
                    <p>Orders<i class="right fas fa-angle-left"></i></p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{{ route('orders.index') }}" class="nav-link {{ isActive(['orders','orders/*']) }}">
                            <i class="far fa-circle nav-icon"></i>
                            <p>All Orders</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link {{ isActive(['']) }}">
                            <i class="far fa-circle nav-icon"></i>
                            <p>All invoices</p>
                        </a>
                    </li>
                </ul>
            </li>
            {{--Orders menu ends--}}

            {{--Reports menu starts--}}
            <li class="nav-item has-treeview {{ isActive(['salaries']) }}">
                <a href="#" class="nav-link {{ isActive(['salaries']) }}">
                <i class="nav-icon fas fa-book"></i>
                    <p>Reports<i class="right fas fa-angle-left"></i></p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{{ route('salaries.index') }}" class="nav-link {{ isActive('salaries') }}">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Monthly Employee Report</p>
                        </a>
                    </li>
                </ul>
            </li>
            {{-- Reports menu ends--}}

            {{--Working Information menu starts--}}
            <li class="nav-item has-treeview {{ isActive(['vehicles','vehicles/*','work_lists','work_lists/*','parts','parts/*']) }}">
                    <a href="#" class="nav-link {{ isActive(['vehicles','vehicles/*','work_lists','work_lists/*','parts','parts/*']) }}">
                        <i class="nav-icon fas fa-fw fa-database"></i>
                        <p>Working Info<i class="right fas fa-angle-left"></i></p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('vehicles.index') }}" class="nav-link {{ isActive(['vehicles','vehicles/*']) }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Vehicle List</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('work_lists.index') }}" class="nav-link {{ isActive(['work_lists','work_lists/*']) }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Work List</p>
                            </a>
                         </li>
                         <li class="nav-item">
                            <a href="{{ route('parts.index') }}" class="nav-link {{ isActive(['parts','parts/*']) }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Parts List</p>
                            </a>
                         </li>
                    </ul>
                </li>
            {{-- Working Information menu ends--}}
            {{--Settings menu starts--}}
            <li class="nav-item has-treeview {{ isActive(['company_settings', 'departments','brands','units']) }}">
                    <a href="#" class="nav-link {{ isActive(['company_settings', 'departments','brands','units']) }}">
                        <i class="nav-icon fas fa-cogs"></i>
                        <p>Settings<i class="right fas fa-angle-left"></i></p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('company_settings.index') }}" class="nav-link {{ isActive('company_settings') }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Company</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('departments.index') }}" class="nav-link {{ isActive('departments') }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Departments</p>
                            </a>
                         </li>
                         <li class="nav-item">
                            <a href="{{ route('units.index') }}" class="nav-link {{ isActive('units') }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Units</p>
                            </a>
                         </li><li class="nav-item">
                            <a href="{{ route('brands.index') }}" class="nav-link {{ isActive('brands') }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Brands</p>
                            </a>
                         </li>
                    </ul>
                </li>
            {{-- Settings menu ends--}}
        </ul>
    </nav>
    <!-- /.sidebar-menu -->
</div>