routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes(['reset' => false, 'register' => false]);

Route::view('test', 'test');

Route::group(['middleware'=>'auth'], function (){

    Route::get('/', 'DashboardController@index')->name('/');

    /*    Resource Controllers starts     */

    Route::resource('products', 'ProductController');

    Route::resource('product_categories', 'ProductCategoryController');

    Route::resource('expenses', 'ExpenseController');

    Route::resource('expense_categories', 'ExpenseCategoryController');

    Route::resource('contractors','ContractorController');

    Route::resource('contractor_types', 'ContractorTypeController');

    Route::resource('measurement_units', 'MeasurementUnitController');

    Route::resource('product_types', 'ProductTypeController');

    Route::resource('product_models', 'ProductModelController');

    Route::resource('company_settings','CompanySettingController');

    Route::resource('vehicles','VehicleController');

    Route::resource('orders','OrderController');
    
	Route::resource('departments','DepartmentController');

	Route::resource('work_lists','WorkListController');

	Route::resource('orderdetails','OrderDetailController');

	Route::resource('customers','CustomerController');

	Route::resource('suppliers', 'SupplierController');

    Route::resource('employees', 'EmployeeController');
    
    Route::resource('attendances', 'AttendanceController');
    /** Salary Routes starts */

    Route::resource('salaries', 'SalaryController');

    Route::get('monthly_salary_dues', 'SalaryController@monthly_salary_dues')->name('monthly_salary_dues');
    
    /** Salary Routes starts */
    Route::resource('parts', 'PartController');

    Route::resource('orders','OrderController');

    Route::resource('materials', 'MaterialController');

    Route::resource('material_types', 'MaterialTypeController');

    Route::resource('material_stocks', 'MaterialStockController');

    Route::resource('brands', 'BrandController');

    Route::resource('units', 'UnitController');

/*    Resource Controllers ends     */


/*    Reports Routes starts     */

    Route::get('report/material', 'ReportController@Material')->name('materials_report');

    Route::get('report/contractor', 'ReportController@Contractor')->name('contractors_report');

    Route::get('delivered_products', 'ReportController@delivered_products')->name('delivered_products');

    Route::get('report/material_product', 'ReportController@MaterialProduct')->name('material_product');


/*    Reports Routes ends     */

/** Material Assignment Routes starts */

    Route::get('assign_material_history', 'AssignMaterialController@index')->name('assign_material_history');

    Route::get('assign_material', 'AssignMaterialController@create')->name('assign_material');

    Route::post('assign_material', 'AssignMaterialController@assignMaterialToProduct')->name('assign_material');

/** Material Assignment Routes ends */

	Route::get('orderDetailupdate/{id}','OrderDetailController@orderDetailupdate');

	Route::get('customer/{phone}','CustomerController@index');
});

/** Cache Clear Routes Starts */

Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    session()->flash('success','Cache Cleared successfull');
    return redirect()->route('/');
});
/** Cache Clear Routes Ends */

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Employee extends Model
{
    use SoftDeletes;
    // Employee Belongs To Department
    
    public function department()
    {
        return $this->belongsTo('App\Department');
    }
    
    public function salaries()
    {
        return $this->hasMany('App\Salary');
    }
   
    public function attendances()
    {
        return $this->hasMany('App\Attendance');
    }
    
    
    public function presents()
    {
        return $this->hasMany('App\Attendance')->where('attendance','p')->count();
    }
    
    public function absents()
    {
        return $this->hasMany('App\Attendance')->where('attendance','a')->count();
    }
     
    public function holydays()
    {
        return $this->hasMany('App\Attendance')->where('attendance','h')->count();
    }
    
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Employee;
use App\Department;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Eloquent\SoftDeletes;

class EmployeeController extends Controller
{
    use SoftDeletes;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::orderBy('department_id')->where(function($employee){
            if(request('name')){
                 $employee->whereHas('user', function($user){
                    $user->where('name',request('name'));
                 });
            }
            if(request('department')){
                $employee->whereHas('department', function($department){
                    $department->where('id',request('department'));
                 });
            }
           
        })->get();
        $departments = Department::all();
        return view('employees.index',compact('employees','departments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $employees = Employee::all();
        $departments = Department::all();
        return view('employees.create', compact('employees','departments'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // retu\rn $request->all();
        $this->validate($request,[
            'name' => 'required',
            'phone' => 'required'
        ]);

        $employee = new Employee();
        $employee->salary = $request->salary;
        $employee->department_id = $request->department_id;
        $employee->name = $request->name;
        $employee->phone = $request->phone;
        $employee->email = $request->email;
        $employee->address = $request->address;
        $employee->password = Hash::make($request->password);
        $employee->joining_date = $request->joining_date;
        $employee->save();
        session()->flash('success','Employee Registration Successful');
        return redirect()->route('employees.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        return view('employees.show',compact('employee'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        $departments = Department::all();
        return view('employees.edit', compact('employee','departments'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        // return $request->all();
        $this->validate($request,[
            'name' => 'required',
            // 'phone' => 'unique:users'
        ]);

        $employee->salary = $request->salary;
        $employee->department_id = $request->department_id;
        $employee->name = $request->name;
        $employee->phone = $request->phone;
        $employee->email = $request->email;
        $employee->address = $request->address;
        $employee->password = Hash::make($request->password);
        $employee->joining_date = $request->joining_date;
        $employee->update();
        session()->flash('success','Employee Registration Successful');
        return redirect()->route('employees.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();
        session()->flash('success','Employee deleted successfully');
        return redirect()->route('employees.index');
    }
}

resources/views/employees/create.blade.php
@extends('layouts.fixed')
@section('title', 'Employees')
@section('content')
<section class="content mt-1">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- form start -->
                <form role="form" action="{{ route('employees.store') }}" method="post" enctype="multipart/form-data">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Employee Register Form</h3>
                        </div><!-- /.card-header -->
                        <div class="card-body">
                            @csrf
                            <div class="row">
                                <div class="col-md-12">
                                    <!-- general form elements -->
                                    <div class="box box-info">
                                        <div class="box-header with-border">
                                            <h3 class="box-title"></h3>
                                        </div>
                                        <!-- /.box-header -->
                                        <!-- form start -->
                                        <form action="{{ route('employees.store') }}" method="post">
                                            @csrf
                                            <div class="box-body">
                                                <div class="form-group row">
                                                    <label for="name" class="col-sm-2 control-label">Name</label>

                                                    <div class="col-sm-10">
                                                        <input type="text" name="name" class="form-control" id="name" placeholder="Enter Employee Name">
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label for="phone" class="col-sm-2 control-label">Phone</label>

                                                    <div class="col-sm-10">
                                                        <input type="phone" name='phone' class="form-control" id="phone"placeholder="Enter Employee Phone">
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label for="joining_date" class="col-sm-2 control-label">Join Date</label>

                                                    <div class="col-sm-10">
                                                        <input type="date" name='joining_date' class="form-control" id="joining_date">
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label for="salary" class="col-sm-2 control-label">Salary</label>

                                                    <div class="col-sm-10">
                                                        <input type="salary" name='salary' class="form-control"id="salary" placeholder="Enter Monthly Salary">
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label for="phone" class="col-sm-2 control-label">Department</label>

                                                    <div class="col-sm-10">
                                                        <select name="department_id" id='department_id' class='form-control'>
                                                            <option selected disabled>Select Department</option>
                                                            @forelse($departments as $department)
                                                            <option value='{{ $department->id }}'>
                                                                {{ $department->name}}</option>
                                                            @empty

                                                            @endforelse
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label for="email"class="col-sm-2 control-label">Email</label>

                                                    <div class="col-sm-10">
                                                        <input type="email" name='email' class="form-control" id="email" placeholder="Enter Employee Email">
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label for="address"
                                                        class="col-sm-2 control-label">Address</label>
                                                    <div class="col-sm-10">
                                                        <textarea name='address' class="form-control" rows="3" placeholder="Enter Employee Address..."></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                            <!-- /.box-body -->
                                            <div class="box-footer"></div>
                                            <!-- /.box-footer -->
                                        </form>
                                    </div>
                                    <!-- /.box -->
                                </div>
                            </div>
                        </div><!-- /.card-body -->
                        <div class="card-footer">
                            <a href="{{ route('employees.index') }}" class="btn btn-danger">Cancel</a>
                            <button type='reset' class="btn btn-primary">Reset Form</button>
                            <button type="submit" class="btn btn-success float-right">Register</button>
                        </div>
                    </div><!-- /.card -->
                </form>
            </div><!-- /.col-md-12 -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
@endsection
@section('script')
<script>

</script>
@endsection

resources/views/employees/index.blade.php
@extends('layouts.fixed')
@section('title', 'Employees')
@section('breadcrumb')
    <li class="breadcrumb-item active">Employees</li>
@endsection
@section('content')
    <section class="content mt-1">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary col-md-12">
                        <div class="card-header row">
                            <h3 class="card-title col-md-3">All Employees <a title="Click to add new product" class="btn btn-sm " href="{{ route('employees.create')}}">
                                <span class="fas fa-plus"></span></a>
                            </h3>
                            <div class="col-md-9">
                                <form class="form-inline float-right" method="GET" action="{{ route('employees.index') }}">
                                    <div class="form-group mx-sm-3">
                                    <label for="name" class="sr-only">Employee Name</label>
                                    <input class="form-control" placeholder="Search Employee" name="name" type="text" value="{{ request('name') }}" id="product">
                                    </div>
                                    <div class="form-group mx-sm-3">
                                        <label for="department" class="sr-only">Department</label>
                                        <select class="form-control" name="department" id="department">
                                            <option value="">Select department</option>
                                            @forelse($departments as $key => $department)
                                                <option {{ request('department') == $department->id ? "selected" : "" }} value="{{ $department->id }}">{{ $department->name }}</option>
                                            @empty
                                            @endforelse
                                        </select>
                                    </div>
                                    <button type="submit" class="btn btn-info btn-round"><i class="fa fa-search"></i></button>
                                  </form>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="tab-content">
                                <div class="table-responsive">
                                    <table class="table table-sm table-striped">
                                        <thead>
                                        <tr class="bg-secondary">
                                            <th class="text-center">SL</th>
                                            <th class="text-center">Name</th>
                                            <th class="text-center">Contact</th>
                                            <th class="text-center">Department</th>
                                            <th class="text-center">Salary</th>
                                            <th class="actions_column">Actions</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @php $sl = 0 @endphp
                                        @forelse($employees as $employee)
                                            <tr>
                                            <td>{{ ++$sl }}</td>
                                                <td class="text-center">
                                                    <a href="{{route('employees.show', $employee->id)}}" class="btn btn-link">{{ $employee->name }}</a></td>
                                                <td class="text-center">{{ $employee->phone }} <br>{{ $employee->email }}</td>
                                                <td class="text-center">{{ $employee->department->name }}</td>
                                                <td class="text-center">{{ number_format($employee->salary,2) }}</td>
                                                <td class="text-center">
                                                <form action="{{route('employees.destroy',$employee->id)}}" method="post"
                                                    onsubmit=" return confirm('Are you sure to delete?')">
                                                    @csrf
                                                    @method('delete')
                                                    <div class="btn-group">
                                                        <button type="button" class="btn btn-info salary_button" data-monthly-amount="{{ number_format($employee->salary,2) }}" data-department-name="{{ $employee->department->name }}" data-employee-id="{{ $employee->id }}" data-employee-name="{{ $employee->name }}" data-toggle="modal" data-target="#modal-sm"><i class="fas fa-handshake"></i></button>
                                                        
                                                        {{--  <a href="#" class="btn btn-success" data-toggle="tooltip" data-placement="auto top" title="Show Status"><i class="fa fa-list"></i></a>  --}}
                                                        <a href="{{ route('employees.edit',1) }}" class="btn btn-warning"><i class="fa fa-edit"></i></a>
                                                         <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button> 
                                                    </div>
                                                </form>
                                                </td>
                                            </tr>
                                        @empty

                                        @endforelse
                                            
                                        </tbody>
                                    </table>
                                    {{-- {{ $products->appends(request()->query())->links() }} --}}
                                </div>
                                <!-- /.tab-pane -->
                            </div>
                            <!-- /.tab-content -->
                        </div><!-- /.card-body -->
                    </div>
                    <!-- /.nav-tabs-custom -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
             <form action="{{ route('salaries.store') }}" method="post">
        @csrf
        <div class="modal fade" id="modal-sm" style="display: none;" aria-hidden="true">
            <div class="modal-dialog ">
            <div class="modal-content">
                <div class="modal-header">
                <h4 class="modal-title">Pay Salary</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                </div>
                <div class="modal-body">
                <div class="card-body box-profile pt-1">
                <div class="text-center">
                  <img class="profile-user-img img-fluid img-circle" src="{{ asset('placeholders/avatar.png')}}" alt="User profile picture">
                </div>

                <h3 class="profile-username text-center mb-0" id="salary_employee_name"></h3>
                <p class="text-muted text-center mb-0" id="salary_department_name"></p>
                <p class="text-center mb-0"><b>Monthly Salary : </b><span id="salary_monthly_amount"></span></p>
                <p class="text-center"><b id="salary_monthly_label_due"></b> <span id="salary_monthly_amount_due" class="text-danger"></span></p>

                <div class="form-group">
                    <label for="year">Salary Year</label>
                    <select name="year" class="form-control" id="year" required>
                        <option value="2019">2019</option>
                        <option value="2020" selected>2020</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="">Salary Month</label>
                    <select name="month" class="form-control" id="month" required>
                        <option value='' selected disabled>Select Month</option>
                        <option value='0'>January</option>
                        <option value='1'>February</option>
                        <option value='2'>March</option>
                        <option value='3'>Aprial</option>
                        <option value='4'>May</option>
                        <option value='5'>June</option>
                        <option value='6'>July</option>
                        <option value='7'>August</option>
                        <option value='8'>September</option>
                        <option value='9'>October</option>
                        <option value='10'>November</option>
                        <option value='11'>December</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="">Salary Amount</label>
                    <input type="number" class="form-control" name="amount" id="" placeholder="Enter amount" required>
                    <input type="hidden" name="employee_id" id="salary_employee_id"/>
                </div>
                </div>
                <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-primary">Pay Now</button>
                </div>
            </div>
            <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
    </form>
        </div><!-- /.container-fluid -->
    </section>
@endsection
@section('script')
    <script>
        $('.salary_button').on('click',function(){
            $('#salary_employee_id').val($(this).attr("data-employee-id"));
            $('#salary_employee_name').text($(this).attr("data-employee-name"));
            $('#salary_department_name').text($(this).attr("data-department-name"));
            $('#salary_monthly_amount').text("TK. " + $(this).attr("data-monthly-amount"));
            $('#salary_monthly_amount_due').text($(this).attr("data-monthly-amount-due"));
        });

        $('#month').on('change',function(){
            var employee_id = $('#salary_employee_id').val();
            var month = $('#month').val();
            var year = $('#year').val();
            $.ajax({
                url: "{{ route('monthly_salary_dues') }}",
                data:{employee_id:employee_id, month:month, year:year},
                type:"get",
                success: function(data){
                  $('#salary_monthly_amount_due').text("Tk. " + data.due);
                  $('#salary_monthly_label_due').text(data.month_name+" Dues: ");
                },
                error: function(errors){
                    console.log(errors)
                }
            });
        });
    </script>
@endsection