routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes(['reset' => false, 'register' => false]);

Route::view('test', 'test');

Route::group(['middleware'=>'auth'], function (){

    Route::get('/', 'DashboardController@index')->name('/');

    /*    Resource Controllers starts     */

    Route::resource('products', 'ProductController');

    Route::resource('product_categories', 'ProductCategoryController');

    Route::resource('expenses', 'ExpenseController');

    Route::resource('expense_categories', 'ExpenseCategoryController');

    Route::resource('contractors','ContractorController');

    Route::resource('contractor_types', 'ContractorTypeController');

    Route::resource('measurement_units', 'MeasurementUnitController');

    Route::resource('product_types', 'ProductTypeController');

    Route::resource('product_models', 'ProductModelController');

    Route::resource('company_settings','CompanySettingController');

    Route::resource('vehicles','VehicleController');

    Route::resource('orders','OrderController');
    
	Route::resource('departments','DepartmentController');

	Route::resource('work_lists','WorkListController');

	Route::resource('orderdetails','OrderDetailController');

	Route::resource('customers','CustomerController');

	Route::resource('suppliers', 'SupplierController');

    Route::resource('employees', 'EmployeeController');
    
    Route::resource('attendances', 'AttendanceController');
    /** Salary Routes starts */

    Route::resource('salaries', 'SalaryController');

    Route::get('monthly_salary_dues', 'SalaryController@monthly_salary_dues')->name('monthly_salary_dues');
    
    /** Salary Routes starts */
    Route::resource('parts', 'PartController');

    Route::resource('orders','OrderController');

    Route::resource('materials', 'MaterialController');

    Route::resource('material_types', 'MaterialTypeController');

    Route::resource('material_stocks', 'MaterialStockController');

    Route::resource('brands', 'BrandController');

    Route::resource('units', 'UnitController');

/*    Resource Controllers ends     */


/*    Reports Routes starts     */

    Route::get('report/material', 'ReportController@Material')->name('materials_report');

    Route::get('report/contractor', 'ReportController@Contractor')->name('contractors_report');

    Route::get('delivered_products', 'ReportController@delivered_products')->name('delivered_products');

    Route::get('report/material_product', 'ReportController@MaterialProduct')->name('material_product');


/*    Reports Routes ends     */

/** Material Assignment Routes starts */

    Route::get('assign_material_history', 'AssignMaterialController@index')->name('assign_material_history');

    Route::get('assign_material', 'AssignMaterialController@create')->name('assign_material');

    Route::post('assign_material', 'AssignMaterialController@assignMaterialToProduct')->name('assign_material');

/** Material Assignment Routes ends */

	Route::get('orderDetailupdate/{id}','OrderDetailController@orderDetailupdate');

	Route::get('customer/{phone}','CustomerController@index');
});

/** Cache Clear Routes Starts */

Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    session()->flash('success','Cache Cleared successfull');
    return redirect()->route('/');
});
/** Cache Clear Routes Ends */

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = ['title','customer_id','vehicle_id','delivery_date', 'note'];

    //A job belongs to a client
    public function customer()
    {
        return $this->belongsTo('App\Customer');
    }
    //A job belongs to a vehicle
    public function vehicle()
    {
        return $this->belongsTo('App\Vehicle');
    }
    // A job has many jobdetails
    public function work_list()
    {
       return $this->hasMany('App\OrderWorkDetail');
    }
    // A job has many jobdetails
    public function part_list()
    {
       return $this->hasMany('App\OrderPartDetail');
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;
use App\User;
use App\Order;
use App\Vehicle;
use App\Customer;
use App\WorkList;
use App\Department;
use App\OrderDetail;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::all();
        return view('orders.index',compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $customers = Customer::all();
        $vehicles = Vehicle::all();
        return view('orders.create',compact('customers','vehicles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'customer_id'=>'required',
            'vehicle_id'=>'required'
        ]);
            $order = new Order;
            $order->customer_id = $request->customer_id;
            $order->vehicle_id = $request->vehicle_id;
            $order->note = $request->customer_note;
            $order->order_no = "Order001";
            $order->delivery = $request->delivery_date;
            $order->save();
            session()->flash('success','Order Added Successfully.');
        return redirect()->route('orders.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        $order = Order::with('owner','vehicle','orderdetails.workLists')->where('id','=',$job_id)->get();
        $orderdetails = OrderDetail::with('workLists.job','workLists.department')->where('job_id','=',$job_id)->get();
        $orderdetails = OrderDetail::with('workLists.job','workLists.department')->where('job_id','=',$job_id)->get();
        $worklist = Department::with('workingLists')->get();


        $deps = Department::all()->KeyBy('name');
        foreach($deps as $d ){
            $deps = OrderDetail::with('workLists.department')->where('job_id','=',$job_id)
            ->wherehas('workLists.department',function($q)use($d){
                $q->where('name','=',$d->name);
            })
            ->get();
                if(count($deps) > 0){
                    $depJobs[$d->name] =$deps;
                }
           }
        return $depJobs;
        return view('orders.edit',compact('job','worklist','jobDetails','$departments','depJobs'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    // public function edit(Order $order)
    public function edit()
    {
        return view('orders.edit');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        //
    }
}

resources/views/orders/create.blade.php
@extends('layouts.fixed')
@section('title', 'Order Create')
@section('breadcrumb')
    <li class="breadcrumb-item active">Orders Create</li>
@stop
@section('content')
<section class="content mt-1">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- form start -->
                <form role="form" action="{{ route('orders.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Order Register Form</h3>
                        </div><!-- /.card-header -->
                        <div class="card-body">
                            @csrf
                            <div class="row">
                                <div class="col-md-12">
                                    <!-- general form elements -->
                                    <div class="box box-info">
                                        <div class="box-header with-border">
                                            <h3 class="box-title"></h3>
                                        </div>
                                        <!-- /.box-header -->
                                        <!-- form start -->
                                        <div class="box-body">
                                            <div class="row" >
                                                <div class="callout callout-warning col">
                                                    <h5>Customer Information <a title="Click to add new customer" class="btn btn-sm text-info" href="{{ route('customers.create')}}"><span class="fas fa-plus"></span></a></h5>
                                                    <div class="form-group row">
                                                        <label for="customer_id" class="col-4 control-label">Customer Phone</label>
                                                        <div class="col-8">
                                                            <select type="text" name="customer_id" class="form-control" id="customer_id" required>
                                                                <option value="" disabled selected>Select Customer</option>
                                                                @forelse($customers as $customer)
                                                                    <option value="{{ $customer->id }}" >{{ $customer->phone .' | '. $customer->name }}</option>
                                                                @empty

                                                                @endforelse
                                                            </select>
                                                            @if($customers->count() == 0)
                                                                <span class="text-danger">No Customer Registered. <br>Please Register customer first</span>
                                                            @endif
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="card bg-light col">
                                                    <div class="card-body pt-0">
                                                        <h2 class="lead"><b>Nicole Pearson</b></h2>
                                                        <p class="text-muted text-sm"><b>About: </b> Web Designer / UX / Graphic Artist / Coffee Lover </p>
                                                        <ul class="ml-4 mb-0 fa-ul text-muted">
                                                            <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Address: Demo Street 123, Demo City 04312, NJ</li>
                                                            <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone #: + 800 - 12 12 23 52</li>
                                                        </ul>
                                                    </div>   
                                                </div>
                                            </div>
                                            <div class="row" >
                                                <div class="callout callout-warning col">
                                                    <h5>Vehicle Information <a title="Click to add new vehicle" class="btn btn-sm text-info" href="{{ route('vehicles.create')}}"><span class="fas fa-plus"></span></a></h5>
                                                    <div class="form-group row">
                                                        <label for="vehicle_id" class="col-4 control-label">Vehicle Plate No</label>
                                                        <div class="col-8">
                                                            <select type="text" name="vehicle_id" class="form-control" id="vehicle_id" required>
                                                                <option value="" disabled selected>Select Vehicle</option>
                                                                @forelse($vehicles as $vehicle)
                                                                    <option value="{{ $vehicle->id }}" >{{ $vehicle->no .' | '. $vehicle->name }}</option>
                                                                @empty

                                                                @endforelse
                                                            </select>
                                                            @if($vehicles->count() == 0)
                                                                <span class="text-danger">No Vehicle Registered. <br>Please Register vehicle first</span>
                                                            @endif
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="card bg-light col">
                                                    <div class="card-body pt-0">
                                                        <h2 class="lead"><b>Nicole Pearson</b></h2>
                                                        <p class="text-muted text-sm"><b>About: </b> Web Designer / UX / Graphic Artist / Coffee Lover </p>
                                                        <ul class="ml-4 mb-0 fa-ul text-muted">
                                                            <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Address: Demo Street 123, Demo City 04312, NJ</li>
                                                            <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone #: + 800 - 12 12 23 52</li>
                                                        </ul>
                                                    </div>   
                                                </div>
                                            </div>
                                            <div class="row" >
                                                <div class="callout callout-warning col">
                                                    <h5>Other Information</h5>
                                                    <div class="row" >
                                                        <div class="form-group col">
                                                            <label for="delivery_date" class="col-sm-6 control-label">Delivery Date</label>

                                                            <div class="col-sm-10">
                                                                <input type="date" name="delivery_date" class="form-control" id="delivery_date" required>
                                                            </div>
                                                        </div>
                                                        <div class="form-group col">
                                                            <label for="name" class="col-sm-6 control-label">Customer Note</label>

                                                            <div class="col-sm-10">
                                                                <textarea name="customer_note" class="form-control" id="customer_note" placeholder="Enter Customer Note"></textarea>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.box-body -->
                                <div class="box-footer col-12">
                                    <a href="{{ route('orders.index') }}" class="btn btn-danger">Cancel</a>
                                    <button type='reset' class="btn btn-primary">Reset Form</button>
                                    <button type="submit" class="btn btn-success float-right">Register</button>
                                </div>
                                <!-- /.box-footer -->
                            </div>
                            <!-- /.box -->
                        </div>
                    </div>
                </div><!-- /.card-body -->
                        <div class="card-footer"></div>
                    </div><!-- /.card -->
                </form>
            </div><!-- /.col-md-12 -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
@endsection
@section('script')
<script>

</script>
@endsection

resources/views/orders/index.blade.php
@extends('layouts.fixed')
@section('title', 'Orders')
@section('breadcrumb')
    <li class="breadcrumb-item active">Orders</li>
@endsection
@section('content')
    <section class="content mt-1">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary col-md-12">
                        <div class="card-header row">
                            <h3 class="card-title col-md-3">All Orders <a title="Click to add new product" class="btn btn-sm " href="{{ route('orders.create')}}">
                                <span class="fas fa-plus"></span></a>
                            </h3>
                            <div class="col-md-9">
                                <form class="form-inline float-right" method="GET" action="{{ route('orders.index') }}">
                                    <div class="form-group mx-sm-3">
                                    <label for="name" class="sr-only">Employee Name</label>
                                    <input class="form-control" placeholder="Employee Name" name="name" type="text" value="{{ request('name') }}" id="product">
                                    </div>
                                    <div class="form-group mx-sm-3">
                                        <label for="department" class="sr-only">Department</label>
                                        <select class="form-control" name="department" id="department">
                                            <option value="">Select department</option>
                                            {{--  @forelse($departments as $key => $department)
                                                <option {{ request('department') == $department->id ? "selected" : "" }} value="{{ $department->id }}">{{ $department->name }}</option>
                                            @empty
                                            @endforelse  --}}
                                        </select>
                                    </div>
                                    <button type="submit" class="btn btn-info btn-round"><i class="fa fa-search"></i></button>
                                  </form>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="tab-content">
                                <div class="table-responsive">
                                    <table class="table table-sm table-striped">
                                        <thead>
                                        <tr class="bg-secondary">
                                            <th class="text-center">SL</th>
                                            <th class="text-center">Order NO</th>
                                            <th class="text-center">Vehicle Details</th>
                                            <th class="text-center">Customer Details</th>
                                            <th class="text-center">Total Works</th>
                                            <th class="text-center">Total Parts</th>
                                            <th class="actions_column">Actions</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @php $sl = 0 @endphp
                                        @forelse($orders as $order)
                                            <tr>
                                                <td>{{ ++$sl }}</td>
                                                <td class="text-center">{{ $order->order_no }}</td>
                                                <td class="text-center">{{ $order->vehicle->name }}</td>
                                                <td class="text-center">{{ $order->customer->name }}</td>
                                                <td class="text-center">{{ $order->work_list->count() }}</td>
                                                <td class="text-center">{{ $order->part_list->count() }}</td>
                                                <td class="text-center">
                                                <form action="#" method="post"
                                                    onsubmit=" return confirm('Are you sure to delete?')">
                                                    @csrf
                                                    @method('delete')
                                                    <div class="btn-group">
                                                        {{--  <button type="button" class="btn btn-info salary_button" data-monthly-amount="{{ $order->salary }}" data-department-name="{{ $order->department->name }}" data-order-id="{{ $order->id }}" data-order-name="{{ $order->name }}" data-toggle="modal" data-target="#modal-sm"><i class="fas fa-handshake"></i></button>  --}}
                                                        {{--  <a href="{{route('orders.show', $order->id)}}" class="btn btn-success"><i class="fa fa-eye"></i></a>  --}}
                                                        {{--  <a href="#" class="btn btn-success" data-toggle="tooltip" data-placement="auto top" title="Show Status"><i class="fa fa-list"></i></a>  --}}
                                                        {{--  <a href="{{ route('orders.edit',1) }}" class="btn btn-warning"><i class="fa fa-edit"></i></a>  --}}
                                                        {{--  <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>  --}}
                                                    </div>
                                                </form>
                                                </td>
                                            </tr>
                                        @empty

                                        @endforelse
                                            
                                        </tbody>
                                    </table>
                                    {{-- {{ $products->appends(request()->query())->links() }} --}}
                                </div>
                                <!-- /.tab-pane -->
                            </div>
                            <!-- /.tab-content -->
                        </div><!-- /.card-body -->
                    </div>
                    <!-- /.nav-tabs-custom -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
             <form action="{{ route('salaries.store') }}" method="post">
        @csrf
        <div class="modal fade" id="modal-sm" style="display: none;" aria-hidden="true">
            <div class="modal-dialog ">
            <div class="modal-content">
                <div class="modal-header">
                <h4 class="modal-title">Pay Salary</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                </div>
                <div class="modal-body">
                <div class="card-body box-profile pt-1">
                <div class="text-center">
                  <img class="profile-user-img img-fluid img-circle" src="{{ asset('placeholders/avatar.png')}}" alt="User profile picture">
                </div>

                <h3 class="profile-username text-center mb-0" id="salary_order_name"></h3>
                <p class="text-muted text-center mb-0" id="salary_department_name"></p>
                <p class="text-center mb-0"><b>Monthly Salary : </b><span id="salary_monthly_amount"></span></p>
                <p class="text-center"><b>Due : </b> <span id="salary_monthly_amount_due">543</span></p>

                <div class="form-group">
                    <label for="year">Salary Year</label>
                    <select name="year" class="form-control" id="year" required>
                        <option value="2019">2019</option>
                        <option value="2020" selected>2020</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="">Salary Month</label>
                    <select name="month" class="form-control" id="month" required>
                        <option value='0'>January</option>
                        <option value='1'>February</option>
                        <option value='2'>March</option>
                        <option value='3'>Aprial</option>
                        <option value='4'>May</option>
                        <option value='5'>June</option>
                        <option value='6'>July</option>
                        <option value='7'>August</option>
                        <option value='8'>September</option>
                        <option value='9'>October</option>
                        <option value='10'>November</option>
                        <option value='11'>December</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="">Salary Amount</label>
                    <input type="number" class="form-control" name="amount" id="" placeholder="Enter amount" required>
                    <input type="hidden" name="order_id" id="salary_order_id"/>
                </div>
                </div>
                <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-primary">Pay Now</button>
                </div>
            </div>
            <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
    </form>
        </div><!-- /.container-fluid -->
    </section>
@endsection
@section('script')
    <script>
        $('.salary_button').on('click',function(){
            $('#salary_order_id').val($(this).attr("data-order-id"));
            $('#salary_order_name').text($(this).attr("data-order-name"));
            $('#salary_department_name').text($(this).attr("data-department-name"));
            $('#salary_monthly_amount').text("TK. " + $(this).attr("data-monthly-amount"));
            {{--  $('#salary_monthly_amount_due').text($(this).attr("data-monthly-amount-due"));  --}}
        })
    </script>
@endsection